config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  constraints subdomain: 'panel' do
    devise_for :panel_user, path: '/'
    root to: 'panel#index'
    get '/escrutados', to: 'panel#escrutado', as: :escrutadas
    get '/:order/resultado/nuevo', to: 'panel#new', as: :new_resultado
    match '/:order/resultado/create', to: 'panel#create', as: :create_resultado, via: %i[post patch]
    get '/:order/resultado/edit', to: 'panel#edit', as: :edit_resultado
    patch '/:order/resultado/update', to: 'panel#update', as: :update_resultado
    get '/proyeccion', to: 'panel#proyeccion', as: :proyeccion
    get '/panel/resultados', to: 'panel#resultados', as: :resultados
    get '/panel/muestreo', to: 'panel#muestreo', as: :muestreo_index
    get '/panel/incidencias', to: 'panel#incidencias', as: :incidencias
    get '/panel/mapa', to: 'panel#mapa', as: :mapa
    get '/panel/mapa-muestreo', to: 'panel#mapa_muestreo', as: :mapa_muestreo
    get '/panel/departamentos', to: 'panel#departamentos', as: :departamentos
    get '/panel/testigos', to: 'panel#testigos', as: :testigos
  end

  # constraints subdomain: 'coordinadores' do
  #   devise_for :coordinadores, path: '/'
  #   root to: 'validate#index'
  #   get '/validacion', to: 'validate#show', as: :validacion
  #   get '/ayuda', to: 'validate#help', as: :help
  #   get '/validacion/:token', to: 'validate#edit_user', as: :edit_user
  #   patch '/validacion/:token', to: 'validate#update_user', as: :update_user
  #   patch '/descartado/:token', to: 'validate#reject_user', as: :reject_user
  # end

  constraints subdomain: 'callcenter' do
    devise_for :callcenter_users, path: '/'
    root to: 'callcenter#index'
    get '/validacion', to: 'callcenter#show', as: :callcenter_validacion
    get '/ayuda', to: 'callcenter#help', as: :callcenter_help
    get '/validacion/:token', to: 'callcenter#edit_user', as: :callcenter_edit_user
    patch '/validacion/:token', to: 'callcenter#update_user', as: :callcenter_update_user
    patch '/descartado/:token', to: 'callcenter#reject_user', as: :callcenter_reject_user
  end

  # get '/' => 'register#new', as: :user
  # get '/iframe' => 'register#iframe', as: :iframe
  # get '/departments' => 'register#get_department'
  # get '/municipalities/:department_id' => 'register#get_municipality'
  # get '/zones/:municipality_id' => 'register#get_zone'
  # get '/posts/:zone_id' => 'register#get_post'
  # post '/' => 'register#create', as: :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope '/api', defaults: { format: 'json' } do
    get 'news' => 'api/news#index', as: :news_index
    get 'user' => 'api/user#show', as: :user_show
    get 'tables', to: 'api/tables#show', as: :tables_show
    post 'issue' => 'api/reports#create', as: :create_issue
    post 'password_reset' => 'api/password#create', as: :password_reset
    post 'user_token' => 'user_token#create', as: :user_token
    post 'user' => 'api/user#update', as: :user_online
    post 'user/email' => 'api/user#email', as: :user_email
    post 'results' => 'api/round#create', as: :create_result
  end
  post '/' => 'application#index', format: 'html'
  get '/token/:token' => 'reset_mail#update', as: :token_show
  get '/verify/:token' => 'reset_mail#validation', as: :validation
  authenticate :admin_user do
    mount Sidekiq::Web => 'admin/sidekiq'
  end
  %w[404 422 500 503].each do |code|
    get code, to: 'errors#show', code: code
  end

  post "/webhook/#{Rails.application.credentials.postal_api}",
       to: 'webhook#handle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/t/:token/accept', to: 'confirmation#accept', as: :confirmation_accept
  # get '/t/:token/reject', to: 'confirmation#reject', as: :confirmation_reject
  # get '/t/:token/edit', to: 'confirmation#edit', as: :confirmation_edit
  # get '/t/:token/coordinador',
      # to: 'confirmation#coordinator', as: :confirmation_coordinator
  # patch '/t/:token', to: 'confirmation#update', as: :confirmation_update
  # patch '/t/:token/coordinador', to: 'confirmation#update_coordinator',
  #       as: :confirmation_update_coordinator
  # get '/t/:token/gracias', to: 'confirmation#thanks', as: :confirmation_thanks
  # get '/t/gracias_coordinador',
  #     to: 'confirmation#thanks_coordinator',
  #     as: :confirmation_thanks_coordinator
end

app/controllers/callcenter_controller.rb
# frozen_string_literal: true

# Callcenter controller
class CallcenterController < ApplicationController
  before_action :authenticate_callcenter_user!
  before_action :set_user, only: %i[update_user reject_user edit_user]
  layout 'app'
  def index; end

  def show
    @user = User.validating.where.not(phone: nil).sample
    if @user
      redirect_to edit_user_path(@user)
    else
      flash[:notice] = 'Todos los coordinadores disponibles '\
        'han sido verificados.'
      redirect_to root_path
    end
  end

  def edit_user; end

  def help; end

  def update_user
    if @user.update_attributes(user_params)
      flash[:notice] = "El coordinador #{@user.name}"\
        'ha sido validado exitosamente!'
      CoordinadorMailer.create(@user.id).deliver_later
      redirect_to root_path
    else
      flash[:alert] = 'Error en el formulario, por favor'\
        'completa todos los campos requeridos'
      render :edit_user
    end
  end

  def reject_user
    @user.assign_attributes(rejected: true)
    if @user.save(validate: false)
      flash[:notice] = "El coordinador #{@user.name}"\
        ' ha sido descartado exitosamente!'
      redirect_to root_path
    else
      flash[:alert] = 'Error en el formulario, por favor '\
        'completa todos los campos requeridos'
      render :edit_user
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email
    ).merge(enabled: true)
  end

  def set_user
    @user = User.find_by(
      token: params[:token],
      coordinator: true
    )
    @user.validate_coordinator = true
  end
end

app/helpers/callcenter_helper.rb
module CallcenterHelper
end

app/views/callcenter/_alert.html.erb
<div class="callout alert">
  <p><%= flash.alert %></p>
</div>

app/views/callcenter/_ayuda.html.erb
<div class="grid-x grid-padding-x">
  <div class="small-12 medium-12 large-8 cell float-center">
    <h4>Hola, a continuación encontrarás las instrucciones a seguir en el sistema:</h4>
    <ol>
      <li>
        <b>Llama, verifica o modifica los datos de cada testigo en tu lista. </b>Pregunta si <b>garantizan su asistencia el 17</b> de junio y si todo es correcto acéptalos. Si no localizas a alguno, descártalo.
      </li>
      <li>
        A los testigos que verificaste, <b>avísales que recibirán un email</b> con instrucciones que deben seguir para validarse como testigos. <b>Pídeles que revisen en su bandeja de entrada o en la carpeta SPAM.</b> Cada testigo que  valide el email recibido quedará listo para ser inscrito en registraduría al cabo de unos días.
      </li>
      <li>
        <b>Crea un canal de Whatsapp sólo para los testigos confirmados, </b>permitirá que tengas una comunicación más ágil y que puedas entregarles  materiales de la campaña.
      </li>
      <li>
        No olvides <b>ayudarles a instalar, actualizar y enseñar a utilizar la APP</b> a todos los testigos, para que puedan participar en los simulacros.  Recuérdales <b>que miren las notificaciones</b> que enviaremos directamente por la app.
      </li>
      <li>
        Si conoces a alguien de confianza que desees que esté en tu puesto como testigo cárgalo a través de <a href="https://petro.com.co/ingreso-testigos/">https://petro.com.co/ingreso-testigos/</a>
      </li>
    </ol>
  </div>
</div>

app/views/callcenter/_callout.html.erb
<div class="callout success">
  <p><%= flash.notice %></p>
</div>

app/views/callcenter/_empty.html.erb
<div class="grid-x grid-padding-x">
  <div class="small-12 medium-12 large-8 cell float-center">
    <%= link_to validacion_path do %>
      <div class="test_vacio">
        <%= fa_icon "plus-square 4x", class: 'far' %>
      </div>
    <% end %>
  </div>
</div>

app/views/callcenter/_lista.html.erb
<div class="grid-container cuerpo">
      <div class="grid-x grid-padding-x">
        <div class="small-12 medium-12 large-10 cell float-center">
          <h4>Hola, a continuación los coordinadores verificados:</h4>
          <table id="lista_test" class="stack">
            <thead>
              <tr>
                <th width="130">Teléfono</th>
                <th width="280">Nombre</th>
                <th width="100">Cédula</th>
                <th>Departamento</th>
                <th>Municipio</th>
                <th>Puesto</th>
              </tr>
            </thead>
            <tbody>
              <% users.joins(:post).uniq.each do |user| %>
                <%= render 'user', user: user %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="grid-x grid-padding-x">
        <div class="small-12 medium-12 large-10 cell float-center">
          <%= link_to validacion_path do %>
            <div class="agregar_mas">
              <%= fa_icon "plus-square 4x", class: 'far' %>
            </div>
          <% end %>
        </div>
      </div>

    </div>

app/views/callcenter/_ocupado.html.erb
<div class="callout alert">
  <p>
    El puesto de este coordinador ya fue asignado, 
    pregunta si desea cambiar de puesto
  </p>
</div>

app/views/callcenter/_user.html.erb
<tr>
  <td><%= tel_to number_to_phone(user.phone, area_code: true) %></td>
  <td><%= user.name %></td>
  <td><%= user.document %></td>
  <td><%= user.post.department.name %></td>
  <td><%= user.post.municipality.name %></td>
  <td><%= user.post.name %></td>
</tr>

app/views/callcenter/edit_user.html.erb
<div class="grid-container c_validacion">
  <% if flash[:alert] %>
    <%= render 'alert' %>
  <% end %>
  <% if @user.post.coordinator %>
    <%= render 'ocupado' %>
  <% end %>
      <div class="grid-x grid-padding-x">
        <div class="small-12 medium-12 large-10 cell float-center">
          <%= semantic_form_for @user, url: update_user_path(@user) do |f| %>
            <%= f.inputs do %>
            <div class="grid-container">
              <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <%= f.input :document, input_html: { disabled: true } %>
                  <%= f.input :document, as: :hidden%>
                </div>
                <div class="medium-6 cell">
                  <%= f.input :name, input_html: { disabled: true, class: 'editable' } %>
                </div>
                <div class="medium-6 cell">
                  <%= f.input :phone, input_html: { disabled: true } %>
                </div>
                <div class="medium-6 cell">
                  <%=
                  f.input :email, input_html: { disabled: @user.email?, class: 'editable'  }
                  %>
                </div>
                <div class="medium-6 cell">
                  <%= f.input :department, input_html: { disabled: true }, as: :string %>
                </div>
                <div class="medium-6 cell">
                  <%= f.input :municipality, input_html: { disabled: true }, as: :string %>
                </div>
                <div class="medium-6 cell">
                  <%= f.input :zone, 
                    input_html: { disabled: true },
                    as: :string %>
                </div>
                <div class="medium-6 cell">
                  <%= f.input :post, 
                    input_html: { disabled: true, class: 'editable' },
                    as: :select,
                    collection: @user.zone.posts.where(coordinator: nil)%>
                </div>
              </div>
              <div class="grid-x grid-margin-x">
                <% edit = capture do %>
                  <%= fa_icon 'edit', class: 'hide-for-small-only' %>
                  Editar
                <% end %>
                <%= f.button edit, type: 'button', class: 'edit warning button small-12 large-2 cell' %>


                  <% verify = capture do %>
                    <%= fa_icon 'check', class: 'hide-for-small-only' %>
                    Verificar
                  <% end %>
                  <%= f.button verify, class: 'verify success button small-12 large-2 cell',  'data-confirm'.to_sym => '¿Estás seguro de que deseas confirmar este testigo?'  %>
                <%= link_to reject_user_path(@user), method: :patch, class: 'alert button small-12 large-2 cell', data: {confirm: "Sólo descarta un testigo cuando no sea posible lograr comunicación.\n¿Estás seguro que deseas descartar este testigo?"} do %>
                  <%= fa_icon "user-times", class: 'hide-for-small-only' %>
                  Descartar
                <% end %>
                <%= link_to validacion_path, class: 'primary button small-12 large-2 large-offset-4 cell end', 'data-confirm'.to_sym => '¿Estás seguro de que deseas pasar al siguiente testigo sin validar?' do %>
                  <%= fa_icon "chevron-right", class: 'hide-for-small-only' %>
                  Siguiente
                <% end %>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

app/views/callcenter/help.html.erb
<div class="grid-container cuerpo">
    <%= render 'ayuda' %>
</div>

app/views/callcenter/index.html.erb
<div class="grid-container cuerpo">

  <% if flash[:notice] %>
    <%= render 'callout' %>
  <% end %>
  <% if User.where(enabled: true, coordinator: true).count == 0 %>
    <%= render 'ayuda' %>
    <%= render 'empty' %>
  <% else %>
    <%= render 'lista', users: User.where(enabled: true, coordinator: true) %>
  <% end %>
</div>